#    ▄▄▄▄▀ ▄  █ ▄███▄       ███   █    ██   ▄█▄    █  █▀ 
# ▀▀▀ █   █   █ █▀   ▀      █  █  █    █ █  █▀ ▀▄  █▄█   
#     █   ██▀▀█ ██▄▄        █ ▀ ▄ █    █▄▄█ █   ▀  █▀▄   
#    █    █   █ █▄   ▄▀     █  ▄▀ ███▄ █  █ █▄  ▄▀ █  █  
#   ▀        █  ▀███▀       ███       ▀   █ ▀███▀    █   
#           ▀                            █          ▀    
#                                       ▀                
#     █ ▄▄   ▄  █ ██   █▄▄▄▄ ██   ████▄  ▄  █            
#     █   █ █   █ █ █  █  ▄▀ █ █  █   █ █   █            
#     █▀▀▀  ██▀▀█ █▄▄█ █▀▀▌  █▄▄█ █   █ ██▀▀█            
#     █     █   █ █  █ █  █  █  █ ▀████ █   █            
#      █       █     █   █      █          █             
#       ▀     ▀     █   ▀      █          ▀              
#                  ▀          ▀                          

# Main background, empty for terminal default
theme[main_bg]=""

# Main text color
theme[main_fg]="#d8c8a9"

# Title color for boxes
theme[title]="#d2bd7d"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7eb7c0"

# Background color of selected item in processes box
theme[selected_bg]="#6296a0"

# Foreground color of selected item in processes box
theme[selected_fg]="#232227"

# Color of inactive/disabled text
theme[inactive_fg]="#968975"

# Color of text appearing on top of graphs
theme[graph_text]="#f0dfbd"

# Background color of the percentage meters
theme[meter_bg]="#736a60"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a58a86"

# Box outline and divider line color
theme[cpu_box]="#d2bd7d"
theme[mem_box]="#898b77"
theme[net_box]="#6296a0"
theme[proc_box]="#a58a86"
theme[div_line]="#736a60"

# Temperature graph color
theme[temp_start]="#898b77"
theme[temp_mid]="#d2bd7d"
theme[temp_end]="#c7927a"

# CPU graph colors
theme[cpu_start]="#7eb7c0"
theme[cpu_mid]="#8f9696"
theme[cpu_end]="#d2bd7d"

# Mem/Disk free meter
theme[free_start]="#8f9696"
theme[free_mid]="#6296a0"
theme[free_end]="#7eb7c0"

# Mem/Disk cached meter
theme[cached_start]="#b4a36f"
theme[cached_mid]="#968975"
theme[cached_end]="#d2bd7d"

# Mem/Disk available meter
theme[available_start]="#6296a0"
theme[available_mid]="#898b77"
theme[available_end]="#d8c8a9"

# Mem/Disk used meter
theme[used_start]="#898b77"
theme[used_mid]="#d2bd7d"
theme[used_end]="#c7927a"

# Download graph colors
theme[download_start]="#b4a36f"
theme[download_mid]="#6296a0"
theme[download_end]="#adb5b4"

# Upload graph colors
theme[upload_start]="#b4a36f"
theme[upload_mid]="#b17f6d"
theme[upload_end]="#c7927a"

# Process box color gradient
theme[process_start]="#6296a0"
theme[process_mid]="#d2bd7d"
theme[process_end]="#c7927a"

# Graph gradient colors
theme[gradient_color_0]="#232227"
theme[gradient_color_1]="#736a60"
theme[gradient_color_2]="#968975"
theme[gradient_color_3]="#898b77"
theme[gradient_color_4]="#6296a0"
theme[gradient_color_5]="#d2bd7d"
theme[gradient_color_6]="#c7927a"
theme[gradient_color_7]="#f0dfbd"

#  ______   __       ______                                       
# /_____/\ /_/\     /_____/\                                      
# \:::_ \ \\:\ \    \:::_ \ \                                     
#  \:\ \ \ \\:\ \    \:\ \ \ \                                    
#   \:\ \ \ \\:\ \____\:\ \ \ \                                   
#    \:\_\ \ \\:\/___/\\:\/.:| |                                  
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#                                                                 