# foot.ini
# By OldJobobo (https://github.com/OldJobobo)
#

[colors-dark]
background=232227
foreground=d8c8a9

regular0=232227
regular1=b17f6d
regular2=898b77
regular3=b4a36f
regular4=8f9696
regular5=a58a86
regular6=6296a0
regular7=d8c8a9

bright0=736a60
bright1=c7927a
bright2=9c9f87
bright3=d2bd7d
bright4=adb5b4
bright5=b79a95
bright6=7eb7c0
bright7=f0dfbd

selection-foreground=232227
selection-background=6296a0
