#    ▄▄▄▄▀ ▄  █ ▄███▄       ███   █    ██   ▄█▄    █  █▀ 
# ▀▀▀ █   █   █ █▀   ▀      █  █  █    █ █  █▀ ▀▄  █▄█   
#     █   ██▀▀█ ██▄▄        █ ▀ ▄ █    █▄▄█ █   ▀  █▀▄   
#    █    █   █ █▄   ▄▀     █  ▄▀ ███▄ █  █ █▄  ▄▀ █  █  
#   ▀        █  ▀███▀       ███       ▀   █ ▀███▀    █   
#           ▀                            █          ▀    
#                                       ▀                
#     █ ▄▄   ▄  █ ██   █▄▄▄▄ ██   ████▄  ▄  █            
#     █   █ █   █ █ █  █  ▄▀ █ █  █   █ █   █            
#     █▀▀▀  ██▀▀█ █▄▄█ █▀▀▌  █▄▄█ █   █ ██▀▀█            
#     █     █   █ █  █ █  █  █  █ ▀████ █   █            
#      █       █     █   █      █          █             
#       ▀     ▀     █   ▀      █          ▀              
#                  ▀          ▀                          

# ghostty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 


# Background and foreground colors
background = #232227
foreground = #d8c8a9

# Standard colors
palette = 0=#232227
palette = 1=#b17f6d
palette = 2=#898b77
palette = 3=#b4a36f
palette = 4=#8f9696
palette = 5=#a58a86
palette = 6=#6296a0
palette = 7=#d8c8a9

# Bright colors
palette = 8=#736a60
palette = 9=#c7927a
palette = 10=#9c9f87
palette = 11=#d2bd7d
palette = 12=#adb5b4
palette = 13=#b79a95
palette = 14=#7eb7c0
palette = 15=#f0dfbd

selection-foreground = #232227
selection-background = #6296a0

#  ______   __       ______                                       
# /_____/\ /_/\     /_____/\                                      
# \:::_ \ \\:\ \    \:::_ \ \                                     
#  \:\ \ \ \\:\ \    \:\ \ \ \                                    
#   \:\ \ \ \\:\ \____\:\ \ \ \                                   
#    \:\_\ \ \\:\/___/\\:\/.:| |                                  
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#                                                                 