#    ▄▄▄▄▀ ▄  █ ▄███▄       ███   █    ██   ▄█▄    █  █▀ 
# ▀▀▀ █   █   █ █▀   ▀      █  █  █    █ █  █▀ ▀▄  █▄█   
#     █   ██▀▀█ ██▄▄        █ ▀ ▄ █    █▄▄█ █   ▀  █▀▄   
#    █    █   █ █▄   ▄▀     █  ▄▀ ███▄ █  █ █▄  ▄▀ █  █  
#   ▀        █  ▀███▀       ███       ▀   █ ▀███▀    █   
#           ▀                            █          ▀    
#                                       ▀                
#     █ ▄▄   ▄  █ ██   █▄▄▄▄ ██   ████▄  ▄  █            
#     █   █ █   █ █ █  █  ▄▀ █ █  █   █ █   █            
#     █▀▀▀  ██▀▀█ █▄▄█ █▀▀▌  █▄▄█ █   █ ██▀▀█            
#     █     █   █ █  █ █  █  █  █ ▀████ █   █            
#      █       █     █   █      █          █             
#       ▀     ▀     █   ▀      █          ▀              
#                  ▀          ▀                          

# kitty.conf
# By OldJobobo (https://github.com/OldJobobo)
# 

background            #232227
foreground            #b7a98d

# black
color0  #232227
color8  #736a60

# red
color1  #b17f6d
color9  #c7927a

# green
color2  #898b77
color10 #9c9f87

# yellow
color3  #b4a36f
color11 #d2bd7d

# blue
color4  #8f9696
color12 #adb5b4

# magenta
color5  #a58a86
color13 #b79a95

#cyan
color6  #6296a0
color14 #7eb7c0

#white
color7  #b7a98d
color15 #c9b99b

selection_foreground #232227
selection_background #6296a0

#  ______   __       ______                                       
# /_____/\ /_/\     /_____/\                                      
# \:::_ \ \\:\ \    \:::_ \ \                                     
#  \:\ \ \ \\:\ \    \:\ \ \ \                                    
#   \:\ \ \ \\:\ \____\:\ \ \ \                                   
#    \:\_\ \ \\:\/___/\\:\/.:| |                                  
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#                                                                 